use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct FlightLegRecord<'a> {
    pub flight_designator: String,
    pub operational_suffix: &'a str,
    pub airline_designator: &'a str,
    pub flight_number: &'a str,
    pub itinerary_variation_identifier: &'a str,
    pub leg_sequence_number: &'a str,
    pub service_type: &'a str,
    pub period_of_operation_from: &'a str,
    pub period_of_operation_to: &'a str,
    pub days_of_operation: &'a str,
    pub frequency_rate: &'a str,
    pub departure_station: &'a str,
    pub scheduled_time_of_passenger_departure: &'a str,
    pub scheduled_time_of_aircraft_departure: &'a str,
    pub time_variation_departure: &'a str,
    pub passenger_terminal_departure: &'a str,
    pub arrival_station: &'a str,
    pub scheduled_time_of_aircraft_arrival: &'a str,
    pub scheduled_time_of_passenger_arrival: &'a str,
    pub time_variation_arrival: &'a str,
    pub passenger_terminal_arrival: &'a str,
    pub aircraft_type: &'a str,
    pub passenger_reservations_booking_designator: &'a str,
    pub passenger_reservations_booking_modifier: &'a str,
    pub meal_service_note: &'a str,
    pub joint_operation_airline_designators: &'a str,
    pub min_connecting_time_status_departure: &'a str,
    pub min_connecting_time_status_arrival: &'a str,
    pub secure_flight_indicator: &'a str,
    pub itinerary_variation_identifier_overflow: &'a str,
    pub aircraft_owner: &'a str,
    pub cockpit_crew_employer: &'a str,
    pub cabin_crew_employer: &'a str,
    pub onward_flight: &'a str,
    pub airline_designator2: &'a str,
    pub flight_number2: &'a str,
    pub aircraft_rotation_layover: &'a str,
    pub operational_suffix2: &'a str,
    pub flight_transit_layover: &'a str,
    pub operating_airline_disclosure: &'a str,
    pub traffic_restriction_code: &'a str,
    pub traffic_restriction_code_leg_overflow_indicator: &'a str,
    pub aircraft_configuration: &'a str,
    pub date_variation: &'a str,
    pub record_type: char,
    pub record_serial_number: &'a str,
}