use serde::{Deserialize, Serialize};
use std::borrow::Cow;

#[derive(Debug, Serialize, Deserialize)]
pub struct FlightLegRecord {
    pub flight_designator: Cow<'static, str>,
    pub operational_suffix: Cow<'static, str>,
    pub airline_designator: Cow<'static, str>,
    pub control_duplicate_indicator: Cow<'static, str>,
    pub flight_number: Cow<'static, str>,
    pub itinerary_variation_identifier: Cow<'static, str>,
    pub leg_sequence_number: Cow<'static, str>,
    pub service_type: Cow<'static, str>,
    pub period_of_operation_from: Cow<'static, str>,
    pub period_of_operation_to: Cow<'static, str>,
    pub days_of_operation: Cow<'static, str>,
    pub frequency_rate: Cow<'static, str>,
    pub departure_station: Cow<'static, str>,
    pub scheduled_time_of_passenger_departure: Cow<'static, str>,
    pub scheduled_time_of_aircraft_departure: Cow<'static, str>,
    pub time_variation_departure: Cow<'static, str>,
    pub passenger_terminal_departure: Cow<'static, str>,
    pub arrival_station: Cow<'static, str>,
    pub scheduled_time_of_aircraft_arrival: Cow<'static, str>,
    pub scheduled_time_of_passenger_arrival: Cow<'static, str>,
    pub time_variation_arrival: Cow<'static, str>,
    pub passenger_terminal_arrival: Cow<'static, str>,
    pub aircraft_type: Cow<'static, str>,
    pub passenger_reservations_booking_designator: Cow<'static, str>,
    pub passenger_reservations_booking_modifier: Cow<'static, str>,
    pub meal_service_note: Cow<'static, str>,
    pub joint_operation_airline_designators: Cow<'static, str>,
    pub min_connecting_time_status_departure: Cow<'static, str>,
    pub min_connecting_time_status_arrival: Cow<'static, str>,
    pub secure_flight_indicator: Cow<'static, str>,
    pub itinerary_variation_identifier_overflow: Cow<'static, str>,
    pub aircraft_owner: Cow<'static, str>,
    pub cockpit_crew_employer: Cow<'static, str>,
    pub cabin_crew_employer: Cow<'static, str>,
    pub onward_flight: Cow<'static, str>,
    pub airline_designator2: Cow<'static, str>,
    pub flight_number2: Cow<'static, str>,
    pub aircraft_rotation_layover: Cow<'static, str>,
    pub operational_suffix2: Cow<'static, str>,
    pub flight_transit_layover: Cow<'static, str>,
    pub operating_airline_disclosure: Cow<'static, str>,
    pub traffic_restriction_code: Cow<'static, str>,
    pub traffic_restriction_code_leg_overflow_indicator: Cow<'static, str>,
    pub aircraft_configuration: Cow<'static, str>,
    pub date_variation: Cow<'static, str>,
    pub record_type: char,
    pub record_serial_number: Cow<'static, str>,
}
