[package]
name = "rustyssim"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rusty-ssim-core.workspace = true

[lib]
name = "rustyssim"
crate-type = ["lib"]