name: test-python.yml
permissions:
  contents: read
on:
  pull_request:
    paths:
      - py-rusty-ssim/**
      - .github/workflows/test-python.yml

  push:
    branches:
      - main
    paths:
      - py-rusty-ssim/**
      - .github/workflows/test-python.yml
    paths-ignore:
      - 'py-rusty-ssim/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: -C debuginfo=0 # Do not produce debug symbols to keep memory usage down
  RUST_BACKTRACE: 1
  PYTHONUTF8: 1


defaults:
  run:
    working-directory: py-rusty-ssim
    shell: bash

jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.9', '3.12', '3.13' ]
        include:
          - os: windows-latest
            python-version: '3.13'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        env:
          BIN: ${{ matrix.os == 'windows-latest' && 'Scripts' || 'bin' }}
        run: |
          python -m venv .venv
          echo "$GITHUB_WORKSPACE/py-rusty-ssim/.venv/$BIN" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/py-rusty-ssim/.venv" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip install uv
          # Install typing-extensions separately whilst the `--extra-index-url` in `requirements-ci.txt`
          # doesn't have an up-to-date typing-extensions, see
          # https://github.com/astral-sh/uv/issues/6028#issuecomment-2287232150
          uv pip install -U typing-extensions
          uv pip install --compile-bytecode -r requirements-dev.txt
      - name: Set up Rust
        run: rustup show

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: py-rusty-ssim
          save-if: ${{ github.ref_name == 'main' }}

      - name: Install rustyssim
        run: maturin develop

      - name: Run tests
        if: github.ref_name != 'main'
        run: pytest
