name: Test Rust

on:
  pull_request:
    paths:
      - rusty-ssim-core/**
      - Cargo.toml
      - .github/workflows/test-rust.yml
  push:
    branches:
      - main
    paths:
      - rusty-ssim-core/**
      - Cargo.toml
      - .github/workflows/test-rust.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref_name == 'main' }}

      - name: Run tests
        if: github.ref_name != 'main'
        run: >
          cargo test --all-features
